---
title: "Beyond force and injuries: Examining alternative (and important) outcomes for police De-escalation training"
date: 2023-11-01
author:
  - Michael D. White
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
  - Carlena Orosco
  - Seth Watts
    #url: https://sbwatts.quarto.pub/sbw/
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
categories:
  - Policing
  - Use of force
  - De-escalation
doi: 10.1016/j.jcrimjus.2023.102129
---
<br>

## Abstract

*Purpose.* The evidence on de-escalation training is limited and has focused almost exclusively on use of force as the primary outcome. We evaluate a de-escalation training program in Tempe, Arizona, delivered via a squad-based randomized controlled trial, using methods that tap into alternative outcomes in encounters that did not involve use of force.

*Methods.* We conducted phone surveys with 282 randomly selected Tempe community members who had a recent encounter with Treatment and Control officers post-training. We also examined body-worn camera footage of 476 randomly selected encounters that occurred pre- (n = 230) and post-training (n = 246) with Treatment and Control officers.

*Results.* Community members reported that trained officers were significantly more likely to use procedural justice and de-escalation; and were more likely to leave them satisfied with their treatment and how their encounter was resolved. Results from BWC footage were less persuasive, though trained officers were more likely to use some de-escalation tactics.

*Conclusions.* Use of force as a singular metric of a training effect is too narrow. A comprehensive assessment of de-escalation training should consider multiple outcomes, including the potential effects in non-force encounters. Random review of BWC footage and community member surveys are two viable methods for achieving this objective.