---
#output: stevetemplates::cv
output: 
 pdf_document: 
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: "Seth Watts" 

jobtitle: Doctoral student
address: School of Criminology and Criminal Justice, Arizona State University
fontawesome: yes
email: swatts12@asu.edu
# phone: 513-335-9275
web: https://sbwatts.quarto.pub/sbw/
updated: yes

#keywords: R Markdown, academic CV, template
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

\pagestyle{plain}
\vspace{4mm}

# Education

*Arizona State University*

PhD, Criminology and Criminal Justice \hfill Expected 2024

*Dissertation*: Fostering Collaborative Solutions in the Opioid Overdose Crisis: Law Enforcement as a Potential Partner in Reducing Fatalities

Certificate, [Social Science Research Methods](https://degrees.apps.asu.edu/masters-phd/major/ASU00/LASSRMGRCT/social-science-research-methods-graduate-certificate)

\vspace{1mm}

MS, Criminology and Criminal Justice  \hfill 2019-2021

*Bowling Green State University* 

BA, Psychology \hfill 2015-2019

\vspace{2mm}
# Research Interests

Policing, Public health, Program evaluation

\vspace{2mm}
# Publications

## Peer-Reviewed

White, M. D., Monk, K., **Watts, S**. (2023). A Half-Century Investigation of Police Officer Line-of-Duty Deaths: Putting Recent Trends in Long-Term Context. *Police Practice and Research*, 1-18. ([DOI](https://www-tandfonline-com.ezproxy1.lib.asu.edu/doi/abs/10.1080/15614263.2023.2267728))

White, M. D., Orosco, C., **Watts, S**. (2023) Beyond Force and Injuries: Examining Alternative (and Important) Outcomes for Police De-escalation Training. *Journal of Criminal Justice*, 89, 102129. ([DOI](https://www-sciencedirect-com.ezproxy1.lib.asu.edu/science/article/pii/S0047235223001009?casa_token=OxErc72pD-QAAAAA:XATyRNg9im-Y4tSAmatE2RofJft49bpMx7c4_fOCiLyqIILE_rMDU03IA2yVHSmdepnLIrpzNfw))

White, D. M., Orosco, C., **Watts, S**. (2023). Can De-escalation Training Reduce Use of Force and Citizen Injury Without Compromising Officer Safety? *Journal of Experimental Criminology*, 1-26. ([DOI](https://link-springer-com.ezproxy1.lib.asu.edu/article/10.1007/s11292-023-09584-8))

White, M. D., **Watts, S**., Orosco, C., Malm, A., Perrone, D. (2022). Leveraging Body-Worn Camera Footage to Better Understand Opioid Overdoses and the Impact of Police-Led Naloxone Programs. *American Journal of Public Health*, *112*(9), 1326-1332. ([DOI](https://ajph.aphapublications.org/doi/abs/10.2105/AJPH.2022.306918))

Gaub, J., White, M., Malm, A., **Watts, S**., Brown, K. (2022). Investigation the Role and Utility of Body-Worn Cameras at the “George Floyd” Protests. *Policing: An International Journal*, *45*(4), 633-647. ([DOI](https://www.emerald.com/insight/content/doi/10.1108/PIJPSM-10-2021-0151/full/html))

White, M. D., Perrone, D., **Watts, S**., Malm, A. (2021). Moving Beyond Narcan: A Police, Social Service, and Researcher Collaborative Response to the Opioid Crisis. *American Journal of Criminal Justice*, *46*(4), 626-643. ([DOI](https://link-springer-com.ezproxy1.lib.asu.edu/article/10.1007/s12103-021-09625-w))

White, M. D., Malm, A., Perrone, D., **Watts, S**. (2021). Narcan Cops: Officer Perceptions of Opioid Use and Willingness to Carry Naloxone. *Journal of Criminal Justice*, 72, 101778. ([DOI](https://www-sciencedirect-com.ezproxy1.lib.asu.edu/science/article/pii/S0047235220302725?casa_token=M3KzLm4DIoUAAAAA:KhQQ6E6WpFcNQdyfTN33-SRHRPttqc81ijlWaNX0wOOYu3TiHBIa17DzDZS2_7K_vU9_CQwdAaA))

\vspace{2mm}
## Working Papers

### Under Review

Brown, K., **Watts, S**., Turner, P., & Wallace, D. How Does Proximity to Service Providers Impact Punitivity in Stop Outcomes for Individuals Experiencing Homelessness?

### In Progress

**Watts, S**., White, M. D., Malm, A., Perrone, D. The Durability of Police Officers’ Attitudes about Naloxone and Opioid Overdose Response: ‘Narcan Cops’ Revisited.

**Watts, S**. LEO Liability When Administering Naloxone.

\vspace{2mm}
## Technical Reports

**Watts, S**., White, M. D., Malm, A., Perrone, D. (2023) The Tempe First-Responder Opioid Recovery Project, Year 4 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

**Watts, S**., White, M. D., Malm, A., Perrone, D. (2022) The Tempe First-Responder Opioid Recovery Project, Year 3 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

White, M. D., **Watts, S**., Malm, A., Perrone, D. (2021) The Tempe First-Responder Opioid Recovery Project, Year 2 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

White, M. D., **Watts, S**., Malm, A., Perrone, D. (2020) The Tempe First-Responder Opioid Recovery Project, Year 1 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

\vspace{2mm}
# Professional Experience

Graduate Research Assistant \hfill 2020-

A Process and Outcome Evaluation of Truleo's Automated Body-Worn Camera Review Technology in Three Arizona Police Departments.
Funded by: Arnold Ventures. 2024 - 2025 ($501,238).
Supervisor: Dr. Michael D. White

The Effect of Automated Body-Camera Review on Officers’ Professionalism and Behavioral Outcomes. 
Funded by: Arnold Ventures. June – December 2023 ($99,980; planning grant).
Supervisor: Dr. Michael D. White

The Tempe First-Responder Opioid Recovery Project
Center for Violence Prevention and Community Safety, School of Criminology and Criminal Justice, Arizona State University. Funded by: Substance Abuse and Mental Health Services administration. 2020 – 2023 ($400,000).
Supervisor: Dr. Michael D. White

Technical Assistance Provider for the National Body-Worn Camera Pilot Implementation Program 
Center for Violence Prevention and Community Safety, School of Criminology and Criminal Justice, Arizona State University. Funded by: Bureau of Justice Assistance. 2020 – 2022 ($800,000).
Supervisor: Dr. Michael D. White 

\vspace{2mm}
Graduate Service Assistant \hfill 2019

Arizona State University, School of Criminology and Criminal Justice
Supervisor: Dr. Cody Telep

\vspace{2mm}
# Media
Crime and Justice News ([Sep, 16, 2022](https://www.ncja.org/crimeandjusticenews/research-backs-police-response-to-drug-overdoses)), Public Health Post ([Sep, 16, 2021](https://www.publichealthpost.org/research/tempe-opioid-recovery/))

\vspace{2mm}
## Conference Presentations^[Presented by coauthor ($P$)]

Gutierrez, S., Mathis, S., Sanuth, A., Watts, S., Wallace, D. (February 2024). Is Law-Violating Driving Behavior Race Specific? Mapping Rates of At-Fault Traffic Accidents by Race. Western Society of Criminology.$^P$

Watts, S., White, M. D., Malm, A., Perrone, D. (November 2023).The Durability of Police Officers’ Attitudes about Naloxone and Opioid Overdose Response: ‘Narcan Cops’ Revisited. American Society of Criminology.

Watts, S., White, M. D., Malm, A., Perrone, D. (November 2022). The Tempe First Responder Opioid Recovery Project. American Society of Criminology.

White, M. D., Watts, S., Orosco, C., Malm, A., Perrone, D (March 2022). Myth busting Police-Led Naloxone Programs with Body-Worn Camera Footage. Academy of Criminal Justice Sciences. 

White, M. D., Orosco, C. A., Watts, S., Malm, A., Perrone, D (2020). The Tempe First Responder Opioid Recovery Project. Southern Criminal Justice Association.$^P$

\vspace{2mm}

## Other Presentations
White, M. D., Watts, S. (2024). Making the Invisible Visible: Body-Worn Cameras as a Tool for Uncovering Bad (and Good) Policing. ASU CCJ Colloquium Series. 

\vspace{2mm}
# Teaching Experience

*Arizona State University*

## Instructor

CRJ: 409 Police accountability (Online) \hfill 2024

CRJ: 201 Crime Control Policies (Online) \hfill 2023

CRJ: 303 Statistical Analyses (Online) \hfill 2023

CRJ: 100 Introduction to Criminal Justice (Online) \hfill 2022

CRJ: 302 Research Methods (Online) \hfill 2022

\vspace{2mm}
## Teaching Assistant
					
CRJ: 230 Introduction to Policing (Online) \hfill 2023

CRJ: 409 Police Accountability \hfill 2023

CRJ: 230 Introduction to Policing (Online) \hfill 2019, 2020

CRJ: 240 Introduction to Corrections (Online) \hfill 2019

\vspace{2mm}
# Activities and Service

## Guest Lectures and Workshops

"[Table-making in Stata](https://github.com/sBwatts/table-making-stata)," workshop at Arizona State University. April 12, 2024.

## Conferences Attended

American Society of Criminology. Philadelphia, Pennsylvania \hfill 2023

American Society of Criminology. Atlanta, Georgia \hfill 2022

Academy of Criminal Justice Sciences. Las Vegas, Nevada \hfill 2022

Center for Undergraduate Research Symposium. Bowling Green, Ohio \hfill 2019

\vspace{2mm}
## Manuscript Reviews

*Journal of Drug Issues*

*Journal of Harm Reduction*

*Police Practice and Research: An International Journal*

\vspace{2mm}
## Professional Development

*Arizona State University* \hfill 2020-

### Workshops

[Statistics, Interpretation, Methods, and Data Workshop](https://sites.google.com/view/simdworkshop/home), [R Workshop](https://jacobtnyoung.github.io/RWorkshop/), Teaching Portfolio Development, Classroom Management and Student Engagement, Creating a Syllabus, Developing a CV/Cover Letter/Research Proposal, Preparing for the Academic Job Market, Overview of Teaching Policies, Writing Advice, Peer-Review Process, Conference Presentations, Organizing and Planning your Career, Academic Writing and Publishing

\vspace{2mm}
## Service to the University

*Arizona State University* \hfill 2021-

Peer Mentorship Program (for first year PhD students), Peer Mentorship Program (for MS students), Reviewer - MS Student’s Application Material for PhD Programs

## Service to the Community

Volunteer in Policing (VIP) Tempe Police Department \hfill 2021-

\vspace{2mm}
# Professional Affiliations

American Society of Criminology

Western Society of Criminology 

\vspace{2mm}
# References

Available upon request.