---
title: "Narcan cops: Officer perceptions of opioid use and willingness to carry naloxone"
date: 2021-01-01
author:
  - Michael D. White
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
  - Dina Perrone
    #affiliation: School of Criminology, Criminal Justice, and Emergency Management, California State     University at Long Beach
    #url: https://sbwatts.quarto.pub/sbw/
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
  - Aili Malm
    #affiliation: School of Criminology, Criminal Justice, and Emergency Management, California State University at Long Beach
  - Seth Watts
    #url: https://sbwatts.quarto.pub/sbw/
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
categories:
  - Policing
  - Naloxone
  - Perceptions
doi: 10.1016/j.jcrimjus.2020.101778 
---
<br>

## Abstract

*Background*: Opioid use has emerged as a significant public health crisis in cities across the United States. In Arizona, opioid overdose deaths increased by 65% from 2016 to 2018, leading the Governor of Arizona to declare a State of Emergency. Because police are often the first to arrive at the scene of an overdose, officers are central to an effective response to the opioid crisis in Arizona and elsewhere. However, many police officers do not carry naloxone, which can immediately reverse the life-threatening effects of an opioid overdose. Few studies examine officer perceptions of opioid use or their willingness to carry and administer naloxone. The degree towhich officers accept this public health responsibility remains unclear.

*Methods*: The authors administered two waves of a survey to patrol officers in the Tempe (AZ) Police Department.The officers completed wave 1 approximately three months before the start of a program that trained and outfitted patrol officers with naloxone. Officers completed wave 2 of the survey several months after the program started. Relying on the Opioid Overdose Knowledge (OOKS), Competence, Concerns, and Attitudes (OOAS) of People who Overdose, and Naloxone-Related Risk Compensation Beliefs (NaRRC-B) scales, the survey captures officer attitudes regarding opioid use, willingness to carry and administer naloxone, and perceptions of their role in responding to the opioid crisis.

*Results*: At wave 1, officers conveyed moderate levels of confidence in recognizing an overdose and providing life-saving care. Officers indicated strong support for carrying naloxone and responding to opioid overdoses, and they recognized the value of treatment for users. At wave 2, officers reported significantly greater confidence and competence in responding to overdoses, and their support for carrying naloxone also increased. Both before and after program start, there was little variation in attitudes across gender, race/ethnicity, education, and length of
service.

*Conclusion*: Officers accept this public health responsibility as part of their mission. Given that officers are frequently first on scene at overdoses and a matter of seconds can determine life or death, police-led naloxone programs will save lives in Tempe and elsewhere.