---
title: "A half-century investigation of police officer line-of-duty deaths: putting the recent spike in long-term context"
date: 2023-11-17
author:
  - Michael D. White
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
  - Khadija Monk
  - Seth Watts
    #url: https://sbwatts.quarto.pub/sbw/
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
categories:
  - Policing
  - Line-of-duty deaths
  - COVID-19
doi: 10.1080/15614263.2023.2267728
---

## Abstract

Research has documented long-term large declines in police line-of-duty deaths over the last 5 decades. The persistence of this decline has been challenged recently by an unprecedented dual threat to officer safety: increased violent attacks on police and the COVID-19 pandemic. We examine all local, county, state, and federal officer line-of-duty deaths from 1970–2021 using data from the Officer Down Memorial Page (ODMP). We examine long-term trends and conduct a decade-by-decade analysis of those deaths. More officers died in 2021 than in any year in the last half-century. Violent killings of police reached the highest level in 20 years, and 523 officers died from COVID-19 in a two-year span. At the state level, there is a significant association between the prevalence of police officer deaths resulting from COVID-19 and general population vaccination rates. We explore the implications of these findings for agency policy and practice with regard to officer safety.
