---
title: "Who is Fatigued? Examining Officer Attitudes Towards PWUOs, Naloxone, and Their Role in Responding to Opioid Overdoses"
date: 2024-11-01
author:
  - Seth Watts
    #url: https://sbwatts.quarto.pub/sbw/
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
  - Michael D. White
    #url: https://sbwatts.quarto.pub/sbw/
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
  - Dina Perrone
    #affiliation: School of Criminology, Criminal Justice, and Emergency Management, California State University at Long Beach
  - Aili Malm
categories:
  - Policing
  - Naloxone
  - Perceptions
  - Compassion fatigue
doi: https://doi.org/10.1016/j.jcrimjus.2024.102308
---
<br>

## Abstract

Many police departments have equipped their officers with naloxone as a promising response to the opioid crisis. Though research suggests police can effectively administer naloxone, recent studies suggest that officers may develop negative attitudes over time as they continually respond to overdoses. This has been described as a “compassion fatigue” effect. We investigate the compassion fatigue hypothesis with a repeated cross-sectional survey of officers in the Tempe, Arizona Police Department. We focus on three outcomes (1) perceptions of officers' role in responding to overdoses, (2) perceptions of naloxone related risk-compensation beliefs, and (3) stigmatizing perceptions of people who use opioids (PWUOs). We run one-way fixed effects regression models to assess if officer attitudes have changed over the study period. Then we run multivariate regression models to test whether officers' opioid overdose response frequency is associated with any of the three outcomes. The findings suggest officers have become more supportive of responding to overdoses but have developed more stigmatizing views of PWUOs over time. This warrants further research attention. However, opioid overdose response frequency was not associated with any of the outcomes. We conclude with a discussion of these findings and their implications for police involvement in the opioid overdose crisis.

<br>

Version: [Post-print](compassion-fatigue-final-postprint1.pdf)

Note: The above post-print is a pre-copyedited, author-produced version of an article accepted for publication in the *Journal of Criminal Justice*. The version of record is available online at [https://doi.org/10.1016/j.jcrimjus.2024.102308](https://doi.org/10.1016/j.jcrimjus.2024.102308).

Citation: Watts, S., White, M. D., Perrone, D., & Malm, A. (2024). Who is fatigued? A repeated cross-sectional survey of officer attitudes towards people who use opioids, naloxone, and their role in responding to opioid overdoses. *Journal of Criminal Justice*, 95, 102308.
