---
title: "Automating body-worn camera footage review through AI: baseline attitudes from a multisite randomized control trial"
date: 2024-10-19
author:
  - Seth Watt
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
  - Michael D. White
  - Aili Malm
    #url: https://sbwatts.quarto.pub/sbw/
    #affiliation: School of Criminology and Criminal Justice, Arizona State University
categories:
  - Policing
  - Artificial intelligence
  - Perceptions
doi: https://doi.org/10.1093/police/paae107
---
<br>

[Pre-print](https://www.crimrxiv.com/pub/8xm0r2jv/release/1)

## Abstract

Body-worn cameras (BWCs) have been widely adopted as a tool to promote police reform. However, studies have shown that most of the footage recorded by BWCs (about 95 per cent) is never reviewed or seen, which undercuts the core benefits of BWCs. Artificial Intelligence-driven analytics may overcome this problem. One example is Truleo, which uses natural language processing to analyse the audio footage and produce metrics of risk and professionalism. However, there is virtually no research examining its use and impact in policing. In the current study, we describe preliminary findings from ongoing randomized controlled trials testing the implementation and impact of Truleo in the Apache Junction and Casa Grande Police Departments. We draw on focus groups of officers, sergeants, and upper-level management and officer perceptions via surveys administered pre-deployment of the technology. We conclude with a discussion of policy implications related to the use of AI for BWC footage review, particularly with regard to how the technology may promote professionalism, intensify supervision, and increase organizational efficiency.