---
title: CV
format:
  quarto-cv-pdf: default
author: Seth Watts
date: last-modified
#phone: 123-456-7890
address: "Arizona State University · Phoenix, AZ"
email: swatts12@asu.edu
fontsize: 11pt
fontfamily: cochineal # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
#github:  # github account
#orcid: 0000-0002-1825-0097 # orcid identifier
#osf: qn8y6 # osf five character id
#twitter: twitter # twitter handle
web: sethbwatts.quarto.pub/sethbwatts
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: peer_bib.bib
  other: other_bib.bib
validate-yaml: false
csl: apa-cv.csl
---

# Education

*Arizona State University*

PhD, Criminology and Criminal Justice \hfill Expected 2024

Dissertation: Fostering Collaborative Solutions in the Opioid Overdose Crisis: Law Enforcement as a Potential Partner in Reducing Fatalities

MS, Criminology and Criminal Justice  \hfill 2021

*Bowling Green State University* 

BA, Psychology \hfill 2019

# Research Interests

Policing, Public health, Program evaluation

## Working Papers

**Watts, S**., White, M. D., & Malm, A. Automating Body-Worn Camera Footage Review through AI: Preliminary Findings from a Multi-Site Randomized Control Trial. Submitted to *Policing: A Journal of Policy and Practice*. [(Pre-print)](https://www.crimrxiv.com/pub/8xm0r2jv/release/1)

**Watts, S**., White, M. D., Malm, A., & Perrone, D. The Durability of Police Officers’ Attitudes about Naloxone and Opioid Overdose Response: ‘Narcan Cops’ Revisited. Submitted to the *Journal of Criminal Justice*.

White, M. D., Orosco, C., & **Watts, S**. More than Use of Force: Examining Alternative Outcomes for Police De-escalation. *Applied Police Briefings*.

**Watts, S**., White, M. D., Malm, A., Orosco, C., & Perrone, D. Understanding Police Involvement at Opioid Overdose Incidents Through Body-Worn Camera Footage. *Applied Police Briefings*.


# Publications

## Peer-Reviewed Journal Articles

Brown, K., **Watts, S**., Turner, P., & Wallace, D. (2024). How Does Proximity to Service Providers Impact Punitivity in Stop Outcomes for Individuals Experiencing Homelessness? *Journal of Crime and Justice*. ([DOI](https://doi-org.ezproxy1.lib.asu.edu/10.1080/0735648X.2024.2375371))

White, M. D., Monk, K., & **Watts, S**. (2023). A Half-Century Investigation of Police Officer Line-of-Duty Deaths: Putting Recent Trends in Long-Term Context. *Police Practice and Research*, 1-18. ([DOI](https://www-tandfonline-com.ezproxy1.lib.asu.edu/doi/abs/10.1080/15614263.2023.2267728))

White, M. D., Orosco, C., & **Watts, S**. (2023) Beyond Force and Injuries: Examining Alternative (and Important) Outcomes for Police De-escalation Training. *Journal of Criminal Justice*, 89, 102129. ([DOI](https://www-sciencedirect-com.ezproxy1.lib.asu.edu/science/article/pii/S0047235223001009?casa_token=OxErc72pD-QAAAAA:XATyRNg9im-Y4tSAmatE2RofJft49bpMx7c4_fOCiLyqIILE_rMDU03IA2yVHSmdepnLIrpzNfw))

White, D. M., Orosco, C., & **Watts, S**. (2023). Can De-escalation Training Reduce Use of Force and Citizen Injury Without Compromising Officer Safety? *Journal of Experimental Criminology*, 1-26. ([DOI](https://link-springer-com.ezproxy1.lib.asu.edu/article/10.1007/s11292-023-09584-8))

White, M. D., **Watts, S**., Orosco, C., Malm, A., & Perrone, D. (2022). Leveraging Body-Worn Camera Footage to Better Understand Opioid Overdoses and the Impact of Police-Led Naloxone Programs. *American Journal of Public Health*, *112*(9), 1326-1332. ([DOI](https://ajph.aphapublications.org/doi/abs/10.2105/AJPH.2022.306918))

Gaub, J., White, M., Malm, A., **Watts, S**., & Brown, K. (2022). Investigation the Role and Utility of Body-Worn Cameras at the “George Floyd” Protests. *Policing: An International Journal*, *45*(4), 633-647. ([DOI](https://www.emerald.com/insight/content/doi/10.1108/PIJPSM-10-2021-0151/full/html))

White, M. D., Perrone, D., &**Watts, S**., & Malm, A. (2021). Moving Beyond Narcan: A Police, Social Service, and Researcher Collaborative Response to the Opioid Crisis. *American Journal of Criminal Justice*, *46*(4), 626-643. ([DOI](https://link-springer-com.ezproxy1.lib.asu.edu/article/10.1007/s12103-021-09625-w))

White, M. D., Malm, A., Perrone, D., & **Watts, S**. (2021). Narcan Cops: Officer Perceptions of Opioid Use and Willingness to Carry Naloxone. *Journal of Criminal Justice*, 72, 101778. ([DOI](https://www-sciencedirect-com.ezproxy1.lib.asu.edu/science/article/pii/S0047235220302725?casa_token=M3KzLm4DIoUAAAAA:KhQQ6E6WpFcNQdyfTN33-SRHRPttqc81ijlWaNX0wOOYu3TiHBIa17DzDZS2_7K_vU9_CQwdAaA))


## Study Pre-registrations

Seth Watts, Michael D. White, & Aili Malm. "A Process and Outcome Evaluation of Automated Body-Worn Camera Review Technology in 3 Arizona Police Departments." [Registered at OSF. Embargoed (pending results).](https://osf.io/vdycb/)

## Technical Reports

White, M. D., Watts, S., Malm, A. A Process and Outcome Evaluation of Automated Body-Worn Camera Review Technology in 3 Arizona Police Departments, 6-month interim report. *Arnold Ventures*.

Watts, S., White, M. D., Malm, A., Perrone, D. (2023) The Tempe First-Responder Opioid Recovery Project, Year 4 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

Watts, S., White, M. D., Malm, A., Perrone, D. (2022) The Tempe First-Responder Opioid Recovery Project, Year 3 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

White, M. D., Watts, S., Malm, A., Perrone, D. (2021) The Tempe First-Responder Opioid Recovery Project, Year 2 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

White, M. D., Watts, S., Malm, A., Perrone, D. (2020) The Tempe First-Responder Opioid Recovery Project, Year 1 Interim Evaluation Report. *Substance Abuse and Mental Health Services Administration*.

# Professional Experience

*Graduate Research Assistant* \hfill 2020-

A Process and Outcome Evaluation of Truleo's Automated Body-Worn Camera Review Technology in Three Arizona Police Departments.
Funded by: Arnold Ventures. 2024 - 2025 ($501,238).
Supervisor: Dr. Michael D. White

The Effect of Automated Body-Camera Review on Officers’ Professionalism and Behavioral Outcomes. 
Funded by: Arnold Ventures. June – December 2023 ($99,980; planning grant).
Supervisor: Dr. Michael D. White

The Tempe First-Responder Opioid Recovery Project
Center for Violence Prevention and Community Safety, School of Criminology and Criminal Justice, Arizona State University. Funded by: Substance Abuse and Mental Health Services administration. 2020 – 2023 ($400,000).
Supervisor: Dr. Michael D. White

Technical Assistance Provider for the National Body-Worn Camera Pilot Implementation Program 
Center for Violence Prevention and Community Safety, School of Criminology and Criminal Justice, Arizona State University. Funded by: Bureau of Justice Assistance. 2020 – 2022 ($800,000).
Supervisor: Dr. Michael D. White 


*Graduate Service Assistant* \hfill 2019

Arizona State University, School of Criminology and Criminal Justice
Supervisor: Dr. Cody Telep


# Media

Goacher, D. (February 8, 2024). Tempe City Council Funds Project Addressing Opioid Overdose Response, Counseling. *Arizona State Press*. ([Link](https://www.statepress.com/article/2024/02/tempe-first-responder-opioid))

Watts, S. (September 16, 2022). Research Backs Police Response To Drug Overdoses. *Crime and Justice News*. ([Link](https://www.ncja.org/crimeandjusticenews/research-backs-police-response-to-drug-overdoses)) 

White D. M., Perrone, D., Malm, A., & Watts, S. (September 16, 2021). The Tempe First-Responder Opioid Recovery Project. *Public Health Post*. ([Link](https://www.publichealthpost.org/research/tempe-opioid-recovery/))


## Conference Presentations^[Presented by coauthor ($P$)]

White, M. D., Watts, S. (June, 2024). Exploring the Drivers of Resistance to Police-Led
Naloxone Programs. American Society of Evidence Based Policing. 

Gutierrez, S., Mathis, S., Sanuth, A., Watts, S., Wallace, D. (February, 2024). Is Law-Violating Driving Behavior Race Specific? Mapping Rates of At-Fault Traffic Accidents by Race. Western Society of Criminology.$^P$

Watts, S., White, M. D., Malm, A., Perrone, D. (November, 2023). The Durability of Police Officers’ Attitudes about Naloxone and Opioid Overdose Response: ‘Narcan Cops’ Revisited. American Society of Criminology.

Watts, S., White, M. D., Malm, A., Perrone, D. (November, 2022). The Tempe First Responder Opioid Recovery Project. American Society of Criminology.

White, M. D., Watts, S., Orosco, C., Malm, A., Perrone, D (March, 2022). Myth busting Police-Led Naloxone Programs with Body-Worn Camera Footage. Academy of Criminal Justice Sciences. 

White, M. D., Orosco, C. A., Watts, S., Malm, A., Perrone, D (2020). The Tempe First Responder Opioid Recovery Project. Southern Criminal Justice Association.$^P$

## Other Presentations

White, M. D., Watts, S. (January, 2024). Making the Invisible Visible: Body-Worn Cameras as a Tool for Uncovering Bad (and Good) Policing. ASU CCJ Colloquium Series. 

# Teaching Experience

*Arizona State University*

## Instructor

CRJ: 409 Police Accountability (Online) \hfill 2024

CRJ: 201 Crime Control Policies (Online) \hfill 2023

CRJ: 303 Statistical Analyses (Online) \hfill 2023

CRJ: 100 Introduction to Criminal Justice (Online) \hfill 2022

CRJ: 302 Research Methods (Online) \hfill 2022


## Teaching Assistant
					
CRJ: 230 Introduction to Policing (Online) \hfill 2019, 2020, 2023

CRJ: 409 Police Accountability \hfill 2023

CRJ: 240 Introduction to Corrections (Online) \hfill 2019


# Activities and Service

## Guest Lectures and Workshops

"[Table-making in Stata](https://github.com/sBwatts/table-making-stata)," workshop at Arizona State University. April 12, 2024.

## Conferences Attended

American Society of Evidence-Based Policing. Spokane, Washington \hfill 2024

American Society of Criminology. Philadelphia, Pennsylvania \hfill 2023

American Society of Criminology. Atlanta, Georgia \hfill 2022

Academy of Criminal Justice Sciences. Las Vegas, Nevada \hfill 2022

Center for Undergraduate Research Symposium. Bowling Green, Ohio \hfill 2019


## Manuscript Reviews

*Criminal Justice & Behavior*

*Journal of Drug Issues*

*Journal of Harm Reduction*

*Police Practice and Research: An International Journal*


## Professional Development

*Arizona State University* \hfill 2020-

### Certifications

[Social Science Research Methods Certificate](https://degrees.apps.asu.edu/masters-phd/major/ASU00/LASSRMGRCT/social-science-research-methods-graduate-certificate), Arizona State University \hfill Expected 2024

- Focus: Program evaluation, quasi-experimental designs (e.g., Difference-in-Differences, Regression Discontinuity, Fixed Effects modeling, Instrumental Variable estimation, Interrupted Time Series/Comparative Interrupted Time Series, Propensity Score Matching), modeling techniques, and model specifications (see [public course material](https://ds4ps.org/pe4ps-textbook/docs/index.html))

### Workshops

[Statistics, Interpretation, Methods, and Data Workshop](https://sites.google.com/view/simdworkshop/home), [R Workshop](https://jacobtnyoung.github.io/RWorkshop/), Teaching Portfolio Development, Classroom Management and Student Engagement, Creating a Syllabus, Developing a CV/Cover Letter/Research Proposal, Preparing for the Academic Job Market, Overview of Teaching Policies, Writing Advice, Peer-Review Process, Conference Presentations, Organizing and Planning your Career, Academic Writing and Publishing


## Service to the University

*Arizona State University* \hfill 2021-

Peer Mentorship Program (for first year PhD students), Peer Mentorship Program (for MS students), Reviewer - MS Student’s Application Material for PhD Programs

## Service to the Community

Volunteer in Policing (VIP) Tempe Police Department \hfill 2021-


# Professional Affiliations

American Society of Evidence-Based Policing

American Society of Criminology

Western Society of Criminology 


# References

[Dr. Michael D. White](https://search.asu.edu/profile/1245788) | Professor, Arizona State University | mdwhite1@asu.edu

[Dr. Jacob T.N. Young](https://search.asu.edu/profile/1791683) | Associate Professor, Arizona State University | jacob.young.1@asu.edu

[Dr. Alyssa W. Chamberlain](https://search.asu.edu/profile/909850) | Associate Professor, Arizona State University | Alyssa.Chamberlain@asu.edu

